# Generated by Django 4.0 on 2022-09-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product',
            new_name='macrame',
        ),
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='product_size',
            new_name='macrame_size',
        ),
    ]
