# Generated by Django 4.0 on 2022-11-01 13:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0002_alter_review_options_alter_macrame_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macrame',
            name='image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
